name: Manual Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'simple'
        type: choice
        options:
        - simple
        - full
      configuration:
        description: 'Build configuration'
        required: true
        default: 'Release'
        type: choice
        options:
        - Debug
        - Release

env:
  XCODE_PROJECT: "PC Controller.xcodeproj"
  XCODE_SCHEME: "PC Controller"
  APP_NAME: "PC Controller"

jobs:
  manual-build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Show build info
      run: |
        echo "Build type: ${{ github.event.inputs.build_type }}"
        echo "Configuration: ${{ github.event.inputs.configuration }}"
        echo "Triggered by: ${{ github.actor }}"
        xcodebuild -version
        
    - name: Clean build folder
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData
        xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"
        
    - name: Create build directory
      run: mkdir -p ./build
        
    - name: Build app
      run: |
        xcodebuild build \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -configuration ${{ github.event.inputs.configuration }} \
          -destination 'platform=macOS' \
          -derivedDataPath ./DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Archive app
      run: |
        xcodebuild archive \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -configuration ${{ github.event.inputs.configuration }} \
          -destination 'platform=macOS' \
          -archivePath ./build/"$APP_NAME".xcarchive \
          -derivedDataPath ./DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Create app bundle
      run: |
        mkdir -p ./build/App
        cp -R ./build/"$APP_NAME".xcarchive/Products/Applications/"$APP_NAME".app ./build/App/
        
    - name: Create DMG
      run: |
        hdiutil create -volname "$APP_NAME" -srcfolder ./build/App -ov -format UDZO ./build/"$APP_NAME".dmg
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Manual-Build-${{ github.event.inputs.build_type }}-${{ github.event.inputs.configuration }}
        path: |
          ./build/App/"$APP_NAME".app
          ./build/"$APP_NAME".dmg
          ./build/"$APP_NAME".xcarchive
        retention-days: 30 